language: shell

dist: xenial
os: linux

services:
  - docker

env:
  - DOCKER_PLATFORM=linux/386,linux/arm64,linux/amd64,linux/arm/v7,linux/arm/v6
    TARGET_IMAGE=djelibeybi/lifx-daydusk

jobs:
  include:
    - stage: deploy
      script: skip
      install: skip
      before_script: skip

      if: type = push

      before_deploy:
        - curl -fsSL https://get.docker.com | sh
        - echo '{"experimental":true}' | sudo tee /etc/docker/daemon.json
        - mkdir -p $HOME/.docker
        - echo '{"experimental":"enabled"}' | sudo tee $HOME/.docker/config.json
        - sudo systemctl restart docker

        - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
        - echo "$DOCKER_TOKEN" | docker login -u "$DOCKER_USERNAME" --password-stdin

      deploy:
        - provider: script
          on:
            tags: true
            branch: main
          script: >-
            docker buildx create --name xbuilder --use && \
            docker buildx build --progress plain --platform $DOCKER_PLATFORM --push -t ${TARGET_IMAGE}:${TRAVIS_TAG} -t ${TARGET_IMAGE}:latest .
        - provider: script
          on:
            all_branches: true
            condition: $TRAVIS_BRANCH != "main"
          script: >-
            docker buildx create --name xbuilder --use && \
            docker buildx build --progress plain --platform $DOCKER_PLATFORM --push -t ${TARGET_IMAGE}:${TRAVIS_BRANCH} .
