#!/usr/bin/with-contenv sh
# shellcheck shell=bash

CONFIG=${CONFIG:-/config/daydusk.yml}

echo "
-------------------------------------
DAY/DUSK CONFIG: ${CONFIG}
-------------------------------------
"

if [ -f "${CONFIG}" ]; then
  LIFX_CONFIG=${CONFIG} /usr/local/bin/python /scripts/generate-crontab.py 2>/dev/null
else
  echo "
-------------------------------------------
CONFIG FILE NOT FOUND! NO EVENTS SCHEDULED!
-------------------------------------------
"
   exit 1
fi
